name: Build
on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      java-version: 21
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup Java ${{ env.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.java-version }}
          distribution: 'temurin'

      - name: Run Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/libs/
